
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - hackhers-mysql-data:/var/lib/mysql
    networks:
      - backend
  
  hackhers-backend-new:
    depends_on:
      - mysqldb
    build: ./hackhers-backend-new/ 
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  hackhers-frontend-new:
    depends_on:
      - hackhers-backend-new
    build:
      context: ./hackhers-frontend-new/ 
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - type: bind
        source: /home/stephanie/hackhers-root/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - frontend  

volumes: 
  hackhers-mysql-data:

networks:
  backend:
  frontend:
